# web port
server:
  #  port: ${server.port}
  port: 8081

# log config
logging:
  config: classpath:logback.xml
  #  path: ${data.path}/applogs/executor/jobhandler
  path: ./data/applogs/executor/jobhandler

datax:
  job:
    admin:
      addresses: http://127.0.0.1:9527
      #addresses: http://127.0.0.1:${datax.admin.port}
    executor:
      appname: datax-executor
      ip:
      #port: 9999
      port: ${executor.port:9999}
      ### job log path
      logpath: ./data/applogs/executor/jobhandler
      #logpath: ${data.path}/applogs/executor/jobhandler
      #logpath: D:\IdeaXm\hmt-web\data\applogs\executor\jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken:

  executor:
    jsonpath: /software/hmt/hmt/bin/
    #jsonpath: D:\IdeaXm\hmt\hmt\bin\

  pypath: /software/hmt/hmt/bin/datax.py
  #pypath: D:\IdeaXm\hmt\hmt\bin\datax.py